language: python
python: 2.7
install: "pip install Lektor"
script: "lektor build"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
deploy:
   provider: script
   script: "lektor deploy master"
   on:
     branch: master
